"""empty message

Revision ID: 0a069b2716d2
Revises: d3b859337860
Create Date: 2023-04-23 02:23:18.650915

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from app.models.user_model import IRoleEnum

# revision identifiers, used by Alembic.
revision = '0a069b2716d2'
down_revision = 'd3b859337860'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(IRoleEnum), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    # ### end Alembic commands ###
